version: "3.9"
services:
  web:
    build: .
    command: ["bash", "migrate.sh"]
    container_name: docker_django
    volumes:
      - .:/dataeden_site
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
    #   - .env.dev
    environment:
      - DB_HOST=db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dataeden
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - 5432:5432
    networks:
      - djangonetwork
networks:
  djangonetwork:
      driver: bridge 
      name: djangonetwork
      ipam:
        driver: default
        options:
          gateway: 172.20.0.1
          subnet: 172.20.0.0/16
          # - hostnames:
          #   - db   
  # db:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: dataeden
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432

volumes:
  postgres_data:
    # driver:local
      
    