# Generated by Django 4.2.3 on 2023-08-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'Email Address', 'verbose_name_plural': 'Email Addresses'},
        ),
    ]
